# Generated by Django 2.0.2 on 2019-01-09 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181202_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=True, max_length=30, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='haha', max_length=32, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='tags',
            name='user',
            field=models.ForeignKey(on_delete=True, to='app.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=True, to='app.Tags', verbose_name='标签'),
            preserve_default=False,
        ),
    ]
