# Generated by Django 2.0.2 on 2019-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190109_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='time',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='app.Tags', verbose_name='标签'),
        ),
    ]
