# Generated by Django 2.0.2 on 2019-01-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190109_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tags', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
    ]
